name: Build & Deploy RSS

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    # Run every 30 minutes on weekdays (UTC)
    - cron: "*/30 6-18 * * 1-5"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS
        run: python scraper.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
